package com.nila.audio

import kotlin.math.PI
import kotlin.math.cos
import kotlin.math.ln
import kotlin.math.log10
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sin
import kotlin.math.sqrt

/**
 * The log-mel frontend, mirrored from ml/src/audio.py.
 *
 * Every constant here has a twin in ml/src/config.py. If the two ever drift the
 * model is fed a different feature space than it was trained on, and the failure
 * is silent -- accuracy just quietly degrades. LogMelFrontendTest pins this
 * implementation against golden vectors generated by the Python reference, so
 * the drift becomes a failing test instead of a mystery.
 *
 * The mel filterbank replicates tf.signal.linear_to_mel_weight_matrix exactly,
 * including its two easily-missed details: the HTK mel formula, and the fact
 * that the DC bin is excluded from the triangle computation and then padded
 * back as a row of zeros.
 */
object LogMelFrontend {

    const val SAMPLE_RATE = 16_000
    const val WIN_LENGTH = 400          // 25 ms
    const val HOP_LENGTH = 160          // 10 ms
    const val N_FFT = 512
    const val N_MELS = 64
    const val FMIN = 125.0
    const val FMAX = 7_500.0
    const val LOG_OFFSET = 1e-3f

    const val PATCH_FRAMES = 96
    const val PATCH_SAMPLES = WIN_LENGTH + HOP_LENGTH * (PATCH_FRAMES - 1)  // 15_600

    private const val SPEC_BINS = N_FFT / 2 + 1                              // 257

    /** Periodic Hann, matching numpy's `hanning(N+1)[:-1]` and tf.signal.hann_window. */
    // Float, not double, and deliberately so. numpy computes the windowed frame
    // in float32 and only promotes to float64 inside the FFT, so windowing in
    // double here would make the phone compute subtly different features than
    // the model was trained on. Near the log floor that gap is visible.
    private val window = FloatArray(WIN_LENGTH) { i ->
        (0.5 - 0.5 * cos(2.0 * PI * i / WIN_LENGTH)).toFloat()
    }

    private val melMatrix: Array<DoubleArray> = buildMelMatrix()

    // Twiddle factors, precomputed once. Looking them up beats the usual
    // recurrence: the recurrence is cheaper per butterfly but compounds rounding
    // error across stages, which is precisely the drift we are avoiding here.
    private val twiddleCos = DoubleArray(N_FFT / 2) { cos(-2.0 * PI * it / N_FFT) }
    private val twiddleSin = DoubleArray(N_FFT / 2) { sin(-2.0 * PI * it / N_FFT) }

    private fun hzToMel(hz: Double) = 2595.0 * log10(1.0 + hz / 700.0)
    private fun melToHz(mel: Double) = 700.0 * (Math.pow(10.0, mel / 2595.0) - 1.0)

    private fun buildMelMatrix(): Array<DoubleArray> {
        val matrix = Array(SPEC_BINS) { DoubleArray(N_MELS) }
        val nyquist = SAMPLE_RATE / 2.0

        // TF drops the DC bin before computing triangles, then pads it back as
        // zeros. Reproducing that offset matters: getting it wrong shifts every
        // filter by one bin, which is a ~30 Hz error at the bottom of the range.
        val binHz = DoubleArray(SPEC_BINS - 1) { i ->
            nyquist * (i + 1).toDouble() / (SPEC_BINS - 1).toDouble()
        }
        val binMel = DoubleArray(SPEC_BINS - 1) { hzToMel(binHz[it]) }

        val lowMel = hzToMel(FMIN)
        val highMel = hzToMel(FMAX)
        val edges = DoubleArray(N_MELS + 2) { i ->
            lowMel + (highMel - lowMel) * i / (N_MELS + 1).toDouble()
        }

        for (m in 0 until N_MELS) {
            val lower = edges[m]
            val center = edges[m + 1]
            val upper = edges[m + 2]
            for (b in binMel.indices) {
                val lowerSlope = (binMel[b] - lower) / (center - lower)
                val upperSlope = (upper - binMel[b]) / (upper - center)
                val w = max(0.0, min(lowerSlope, upperSlope))
                matrix[b + 1][m] = w                   // +1 restores the DC row
            }
        }
        return matrix
    }

    /** Frame count this frontend will emit for a buffer of [samples] length. */
    fun frameCount(samples: Int): Int =
        if (samples < WIN_LENGTH) 0 else 1 + (samples - WIN_LENGTH) / HOP_LENGTH

    /**
     * Compute log-mel into [out], laid out row-major as `[frame][mel]`.
     *
     * Writes into a caller-supplied array rather than allocating, because this
     * runs a few times a second for hours and the allocation churn would show up
     * as GC pauses in the audio thread.
     */
    fun logMel(wave: FloatArray, offset: Int, length: Int, out: FloatArray): Int {
        val frames = frameCount(length)
        require(out.size >= frames * N_MELS) {
            "output buffer too small: need ${frames * N_MELS}, got ${out.size}"
        }

        // Double precision through the transform. The frontend must agree with
        // the numpy reference to well under the training noise floor, and single
        // precision accumulates enough error across 9 butterfly stages to drift
        // past that -- which the golden-vector test catches.
        val re = DoubleArray(N_FFT)
        val im = DoubleArray(N_FFT)
        val mag = DoubleArray(SPEC_BINS)

        for (f in 0 until frames) {
            val start = offset + f * HOP_LENGTH
            java.util.Arrays.fill(re, 0.0)
            java.util.Arrays.fill(im, 0.0)
            // float32 multiply, then promote -- matching numpy's dtype ladder.
            for (i in 0 until WIN_LENGTH) {
                re[i] = (wave[start + i] * window[i]).toDouble()
            }

            fft(re, im)
            for (b in 0 until SPEC_BINS) mag[b] = sqrt(re[b] * re[b] + im[b] * im[b])

            val base = f * N_MELS
            for (m in 0 until N_MELS) {
                var acc = 0.0
                for (b in 0 until SPEC_BINS) {
                    val w = melMatrix[b][m]
                    if (w != 0.0) acc += mag[b] * w
                }
                out[base + m] = ln(acc + LOG_OFFSET).toFloat()
            }
        }
        return frames
    }

    /** One 0.96 s patch, shaped `[PATCH_FRAMES * N_MELS]`, ready for the interpreter. */
    fun patch(wave: FloatArray, offset: Int, out: FloatArray): Boolean {
        if (offset + PATCH_SAMPLES > wave.size) return false
        logMel(wave, offset, PATCH_SAMPLES, out)
        return true
    }

    fun dbfs(wave: FloatArray, offset: Int, length: Int): Float {
        var sum = 0.0
        for (i in offset until offset + length) {
            val v = wave[i].toDouble()
            sum += v * v
        }
        val rms = sqrt(sum / length)
        return (20.0 * log10(max(rms, 1e-9))).toFloat()
    }

    /** In-place iterative radix-2 Cooley-Tukey. N_FFT is 512, so no padding logic. */
    private fun fft(re: DoubleArray, im: DoubleArray) {
        val n = re.size
        var j = 0
        for (i in 1 until n) {
            var bit = n shr 1
            while (j and bit != 0) {
                j = j xor bit
                bit = bit shr 1
            }
            j = j or bit
            if (i < j) {
                var t = re[i]; re[i] = re[j]; re[j] = t
                t = im[i]; im[i] = im[j]; im[j] = t
            }
        }

        var len = 2
        while (len <= n) {
            val half = len shr 1
            val stride = n / len
            var i = 0
            while (i < n) {
                for (k in 0 until half) {
                    val tw = k * stride
                    val wRe = twiddleCos[tw]
                    val wIm = twiddleSin[tw]
                    val a = i + k
                    val b = a + half
                    val vRe = re[b] * wRe - im[b] * wIm
                    val vIm = re[b] * wIm + im[b] * wRe
                    re[b] = re[a] - vRe
                    im[b] = im[a] - vIm
                    re[a] += vRe
                    im[a] += vIm
                }
                i += len
            }
            len = len shl 1
        }
    }
}
