package com.nila.audio

/**
 * GENERATED by ml/src/emit_android.py on 2026-09-06 -- do not edit.
 *
 * These are the numbers our own evaluation produced, on a split where no infant
 * appears in both training and test. They are generated rather than typed so
 * that the reliability the app claims cannot drift from the reliability it was
 * measured to have.
 */
object ModelCard {

    const val GENERATED_ON = "2026-09-06"

    // ---- cry detection: deployable -------------------------------------
    const val DETECT_SUBJECT_WISE_AUC = 0.9923f
    const val DETECT_ACCURACY = 0.9606f
    const val DETECT_BALANCED_ACCURACY = 0.9653f
    const val DETECT_MACRO_F1 = 0.9418f
    const val DETECT_RECALL_CRY = 0.9731f
    const val DETECT_RECALL_NOT_CRY = 0.9575f
    const val DETECT_TEST_CLIPS = 2946

    // ---- cry reason: measured, and it did not transfer ------------------
    const val REASON_SUBJECT_WISE_AUC = 0.4437f
    const val REASON_ACCURACY = 0.5827f
    const val REASON_MACRO_F1 = 0.1719f
    const val REASON_MAJORITY_BASELINE = 0.7559f
    const val REASON_TEST_CLIPS = 762

    /**
     * False when the reason head failed to beat chance on unseen infants.
     *
     * When this is false the UI must not print a cause as a fact. It may show
     * the hypothesis alongside this number, because a hypothesis carrying its
     * own validation result is honest; a bare label is not.
     */
    const val REASON_TRUSTWORTHY = false

    // ---- the same model under the protocol we argue against -------------
    const val REASON_LEAKY_AUC = 0.9532f
    const val REASON_LEAKY_ACCURACY = 0.7541f

    /** What the evaluation protocol alone is worth, in macro AUC. */
    const val LEAKAGE_AUC_INFLATION = 0.5095f

    // ---- an unrelated model family, same outcome ------------------------
    // A 461-feature Random Forest -- different features, different algorithm,
    // no shared code with the CNN -- lands in the same place on the same
    // infants. Two independent approaches failing identically is what turns
    // "our model did not work" into "this is not learnable from this data".
    const val RF_HONEST_AUC = 0.4615f
    const val RF_CONTAMINATED_AUC = 0.9898f

    // ---- best coarser grouping we could find ----------------------------
    const val BEST_GROUPING = "hungry_vs_rest"
    const val BEST_GROUPING_AUC = 0.4970f

    /** One line, safe to put on screen, that states the limit plainly. */
    val honestSummary: String
        get() = if (REASON_TRUSTWORTHY) {
            "Cause estimate validated at %.2f AUC on infants it has never heard."
                .format(REASON_SUBJECT_WISE_AUC)
        } else {
            // Parenthesised: `.format()` binds to the last literal in a `+`
            // chain, so an unparenthesised version silently leaves earlier
            // specifiers as literal text.
            (
                "We can tell you the baby is crying, not why. On infants it " +
                    "had never heard, the cause model scored %.2f AUC -- " +
                    "chance is 0.50."
                ).format(REASON_SUBJECT_WISE_AUC)
        }
}
