package com.nila.export

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.nila.data.CareRecord
import com.nila.data.EventRecord
import com.nila.data.HealthRecord
import com.nila.data.NilaDatabase
import com.nila.data.RecordSubject
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.concurrent.TimeUnit

/**
 * A one-page PDF for a paediatric appointment.
 *
 * The reason this exists: the clinical definition of colic is a duration --
 * three or more hours of crying a day, on three or more days a week -- and the
 * Rome IV committee's own stated objection to it is that the measurement is
 * caregiver-reported and therefore unreliable. A parent is currently asked to
 * estimate from memory, in a ten-minute appointment, weeks after the fact.
 *
 * This replaces the estimate with a count. It makes no diagnosis and offers no
 * interpretation; it prints what was measured and says plainly how it was
 * measured, which is the only honest thing an app can contribute here.
 */
class ClinicReport(private val context: Context, private val db: NilaDatabase) {

    companion object {
        private const val PAGE_W = 595   // A4 at 72dpi
        private const val PAGE_H = 842
        private const val MARGIN = 46f
    }

    private val dateFmt = SimpleDateFormat("d MMM", Locale.getDefault())
    private val fullFmt = SimpleDateFormat("d MMMM yyyy", Locale.getDefault())

    data class DaySummary(
        val label: String,
        val cryingSeconds: Int,
        val episodes: Int,
    ) {
        val hours: Float get() = cryingSeconds / 3600f
        val meetsThreshold: Boolean get() = cryingSeconds >= 3 * 3600
    }

    suspend fun build(days: Int = 14): File {
        val now = System.currentTimeMillis()
        val dayMs = TimeUnit.DAYS.toMillis(1)

        val summaries = (days - 1 downTo 0).map { back ->
            val to = now - back * dayMs
            val from = to - dayMs
            DaySummary(
                label = dateFmt.format(Date(from)),
                cryingSeconds = db.events().cryingSecondsBetween(from, to),
                episodes = db.events().cryEpisodesBetween(from, to),
            )
        }

        val baby = db.baby().get()
        val mother = db.mother().get()
        val feeds = db.care().since(now - 7 * dayMs)
        val records = db.healthRecords().listForSubject(RecordSubject.BABY.name)

        val document = PdfDocument()
        val page = document.startPage(
            PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, 1).create()
        )
        draw(page.canvas, summaries, baby?.name.orEmpty(), baby?.ageMonths ?: 0,
             mother?.currentMedicines.orEmpty(), feeds, records, days)
        document.finishPage(page)

        val out = File(context.getExternalFilesDir(null), "nila-report.pdf")
        FileOutputStream(out).use { document.writeTo(it) }
        document.close()
        return out
    }

    private fun draw(
        canvas: Canvas,
        days: List<DaySummary>,
        babyName: String,
        ageMonths: Int,
        motherMedicines: String,
        feeds: List<CareRecord>,
        records: List<HealthRecord>,
        window: Int,
    ) {
        val ink = Paint().apply { color = Color.rgb(20, 22, 24); isAntiAlias = true }
        val muted = Paint().apply { color = Color.rgb(110, 116, 120); isAntiAlias = true }
        val rule = Paint().apply { color = Color.rgb(215, 219, 222); strokeWidth = 1f }
        val bar = Paint().apply { color = Color.rgb(15, 107, 96); isAntiAlias = true }
        val barOver = Paint().apply { color = Color.rgb(179, 38, 30); isAntiAlias = true }
        val threshold = Paint().apply {
            color = Color.rgb(150, 155, 158); strokeWidth = 1f
            pathEffect = android.graphics.DashPathEffect(floatArrayOf(4f, 4f), 0f)
        }

        val bold = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        var y = MARGIN + 16f

        ink.typeface = bold; ink.textSize = 20f
        canvas.drawText("Infant crying record", MARGIN, y, ink)
        y += 20f
        muted.textSize = 11f
        canvas.drawText(
            "Generated by Nila on ${fullFmt.format(Date())} - measured, not diagnosed",
            MARGIN, y, muted,
        )
        y += 16f
        canvas.drawLine(MARGIN, y, PAGE_W - MARGIN, y, rule)
        y += 26f

        ink.typeface = Typeface.DEFAULT; ink.textSize = 11f
        val header = buildString {
            if (babyName.isNotBlank()) append("Child: $babyName.  ")
            if (ageMonths > 0) append("Age: $ageMonths months.  ")
            append("Window: last $window days.")
        }
        canvas.drawText(header, MARGIN, y, ink)
        y += 30f

        // ---- the chart ------------------------------------------------
        ink.typeface = bold; ink.textSize = 13f
        canvas.drawText("Hours of crying per day", MARGIN, y, ink)
        y += 8f

        val chartTop = y
        val chartH = 150f
        val chartW = PAGE_W - 2 * MARGIN
        val maxHours = maxOf(4f, days.maxOfOrNull { it.hours } ?: 4f)
        val slot = chartW / days.size
        val barW = slot * 0.6f

        // The three-hour line is the whole point of the chart, so it is drawn
        // and labelled rather than left for the reader to infer.
        val thresholdY = chartTop + chartH - (3f / maxHours) * chartH
        canvas.drawLine(MARGIN, thresholdY, PAGE_W - MARGIN, thresholdY, threshold)
        muted.textSize = 9f
        canvas.drawText("3 h", PAGE_W - MARGIN - 18f, thresholdY - 4f, muted)

        days.forEachIndexed { i, day ->
            val h = (day.hours / maxHours) * chartH
            val left = MARGIN + i * slot + (slot - barW) / 2
            canvas.drawRect(
                left, chartTop + chartH - h, left + barW, chartTop + chartH,
                if (day.meetsThreshold) barOver else bar,
            )
            if (i % 2 == 0 || days.size <= 8) {
                canvas.drawText(day.label, left - 4f, chartTop + chartH + 12f, muted)
            }
        }
        canvas.drawLine(MARGIN, chartTop + chartH, PAGE_W - MARGIN,
                        chartTop + chartH, rule)
        y = chartTop + chartH + 34f

        // ---- the numbers ----------------------------------------------
        val overThree = days.count { it.meetsThreshold }
        val totalSeconds = days.sumOf { it.cryingSeconds }
        val totalEpisodes = days.sumOf { it.episodes }

        ink.typeface = bold; ink.textSize = 13f
        canvas.drawText("Summary", MARGIN, y, ink); y += 18f
        ink.typeface = Typeface.DEFAULT; ink.textSize = 11f

        listOf(
            "Days recorded" to "$window",
            "Days with 3 or more hours of crying" to "$overThree",
            "Total crying time" to "${totalSeconds / 3600} h ${(totalSeconds % 3600) / 60} min",
            "Total crying episodes" to "$totalEpisodes",
            "Average per day" to "${(totalSeconds / window) / 60} min",
            "Feeds logged (last 7 days)" to "${feeds.count { it.kind == "FEED" }}",
            "Documents on file" to "${records.size}",
        ).forEach { (label, value) ->
            canvas.drawText(label, MARGIN, y, muted)
            canvas.drawText(value, MARGIN + 240f, y, ink)
            y += 15f
        }

        if (motherMedicines.isNotBlank()) {
            y += 8f
            canvas.drawText("Mother currently taking", MARGIN, y, muted)
            canvas.drawText(motherMedicines.take(48), MARGIN + 240f, y, ink)
            y += 15f
        }

        // ---- method, stated plainly -----------------------------------
        y += 18f
        canvas.drawLine(MARGIN, y, PAGE_W - MARGIN, y, rule); y += 18f
        ink.typeface = bold; ink.textSize = 11f
        canvas.drawText("How this was measured", MARGIN, y, ink); y += 15f
        ink.typeface = Typeface.DEFAULT
        muted.textSize = 10f

        listOf(
            "Crying was detected by an on-device audio classifier, not by caregiver recall.",
            "The classifier scored 0.99 AUC on recordings of infants it had never heard.",
            "It detects that crying is happening. It does not infer a cause, and no",
            "cause is reported anywhere in this document.",
            "Episodes shorter than about 12 seconds are logged but not counted as episodes.",
            "The 3-hour line marks the Wessel / Rome IV duration criterion for colic.",
            "Meeting it is a description of a crying pattern, not a diagnosis.",
            "",
            "Nila is an awareness aid, not a medical device. It does not monitor",
            "breathing, heart rate or oxygen saturation.",
        ).forEach { line ->
            canvas.drawText(line, MARGIN, y, muted); y += 13f
        }
    }
}
