package com.nila.audio

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.math.abs

/**
 * Pins the Kotlin frontend to the Python reference in ml/src/audio.py.
 *
 * The fixture is generated by ml/src/make_golden.py. If someone changes a
 * constant on one side without regenerating and retraining, this fails --
 * which is the entire point, because the alternative symptom is a model that
 * silently gets worse and nobody knows why.
 */
class LogMelFrontendTest {

    private val tolerance = 2e-3f

    private fun golden(): JSONObject {
        val stream = javaClass.classLoader!!.getResourceAsStream("logmel_golden.json")
            ?: error("logmel_golden.json missing - run ml/src/make_golden.py")
        return JSONObject(stream.bufferedReader().use { it.readText() })
    }

    @Test
    fun `spec constants match the training pipeline`() {
        val spec = golden().getJSONObject("spec")
        assertEquals(spec.getInt("sample_rate"), LogMelFrontend.SAMPLE_RATE)
        assertEquals(spec.getInt("win_length"), LogMelFrontend.WIN_LENGTH)
        assertEquals(spec.getInt("hop_length"), LogMelFrontend.HOP_LENGTH)
        assertEquals(spec.getInt("n_fft"), LogMelFrontend.N_FFT)
        assertEquals(spec.getInt("n_mels"), LogMelFrontend.N_MELS)
        assertEquals(spec.getInt("patch_frames"), LogMelFrontend.PATCH_FRAMES)
        assertEquals(spec.getInt("patch_samples"), LogMelFrontend.PATCH_SAMPLES)
        assertEquals(spec.getDouble("fmin"), LogMelFrontend.FMIN, 1e-9)
        assertEquals(spec.getDouble("fmax"), LogMelFrontend.FMAX, 1e-9)
    }

    @Test
    fun `log-mel output matches the python reference`() {
        val cases = golden().getJSONArray("cases")
        var checked = 0

        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val name = case.getString("name")

            val inputJson = case.getJSONArray("input")
            val wave = FloatArray(inputJson.length()) {
                inputJson.getDouble(it).toFloat()
            }

            val out = FloatArray(LogMelFrontend.PATCH_FRAMES * LogMelFrontend.N_MELS)
            val frames = LogMelFrontend.logMel(wave, 0, wave.size, out)
            assertEquals("$name: frame count", LogMelFrontend.PATCH_FRAMES, frames)

            fun frameAt(index: Int) = FloatArray(LogMelFrontend.N_MELS) {
                out[index * LogMelFrontend.N_MELS + it]
            }

            val checks = listOf(
                "first_frame" to frameAt(0),
                "middle_frame" to frameAt(LogMelFrontend.PATCH_FRAMES / 2),
                "last_frame" to frameAt(LogMelFrontend.PATCH_FRAMES - 1),
            )

            for ((key, actual) in checks) {
                val expected = case.getJSONArray(key)
                // Collect every mismatch before failing. One bin's diff tells
                // you almost nothing; "4 of 64 bins, all at the log floor" tells
                // you exactly where to look.
                var worst = 0f
                var worstBin = -1
                var mismatches = 0
                for (m in 0 until expected.length()) {
                    val want = expected.getDouble(m).toFloat()
                    val diff = abs(want - actual[m])
                    if (diff > tolerance) mismatches++
                    if (diff > worst) { worst = diff; worstBin = m }
                    checked++
                }
                assertTrue(
                    "$name.$key: $mismatches/${expected.length()} bins outside " +
                        "$tolerance. Worst bin $worstBin: expected " +
                        "${expected.getDouble(worstBin)}, got ${actual[worstBin]} " +
                        "(diff $worst)",
                    mismatches == 0,
                )
            }

            // Per-frame sums catch a filterbank that is right at the edges and
            // wrong in the middle, which the three sampled frames could miss.
            val sums = case.getJSONArray("frame_sums")
            for (f in 0 until sums.length()) {
                val want = sums.getDouble(f).toFloat()
                var got = 0f
                for (m in 0 until LogMelFrontend.N_MELS) {
                    got += out[f * LogMelFrontend.N_MELS + m]
                }
                assertTrue(
                    "$name.frame_sums[$f]: expected $want, got $got",
                    abs(want - got) <= tolerance * LogMelFrontend.N_MELS,
                )
            }
        }
        assertTrue("expected to check many values, checked $checked", checked > 500)
    }

    @Test
    fun `frame count matches the training framing rule`() {
        assertEquals(0, LogMelFrontend.frameCount(399))
        assertEquals(1, LogMelFrontend.frameCount(400))
        assertEquals(2, LogMelFrontend.frameCount(560))
        assertEquals(
            LogMelFrontend.PATCH_FRAMES,
            LogMelFrontend.frameCount(LogMelFrontend.PATCH_SAMPLES),
        )
    }

    @Test
    fun `dbfs is sane at known levels`() {
        val silence = FloatArray(16_000)
        assertTrue(LogMelFrontend.dbfs(silence, 0, silence.size) < -100f)

        val fullScale = FloatArray(16_000) { if (it % 2 == 0) 1f else -1f }
        assertEquals(0f, LogMelFrontend.dbfs(fullScale, 0, fullScale.size), 0.1f)

        val halfScale = FloatArray(16_000) { if (it % 2 == 0) 0.5f else -0.5f }
        assertEquals(-6.02f, LogMelFrontend.dbfs(halfScale, 0, halfScale.size), 0.1f)
    }
}
