"""
Ship the trained artefacts into the Android project.

Copies the exported .tflite files into app/src/main/assets and generates
ModelCard.kt from the evaluation reports.

Generating the model card rather than hand-writing it is the point. The numbers
the app shows about its own reliability are the numbers the evaluation actually
produced -- if a retrain makes the reason head worse, the app says so on the
next build without anyone remembering to update a constant.
"""

import json
import shutil
from datetime import date

from config import MODELS, REPORTS

ANDROID = MODELS.parents[1] / "android" / "app" / "src" / "main"
ASSETS = ANDROID / "assets"
KOTLIN = ANDROID / "java" / "com" / "nila" / "audio"

# A reason head is only allowed to show a label if it beats this on a
# subject-wise split. 0.60 macro AUC is a low bar deliberately -- we are not
# asking for excellence, only for evidence that it learned anything that
# transfers to an infant it has never heard.
TRUST_AUC_THRESHOLD = 0.60


def test_metrics(name: str) -> dict:
    report = json.loads((REPORTS / f"{name}.json").read_text())
    return next(m for m in report["metrics"] if m["split"] == "test")


def main() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)

    copied = []
    for stem in ("detect", "reason"):
        for variant in ("mel", "wave"):
            src = MODELS / f"{stem}_{variant}.tflite"
            if src.exists():
                shutil.copy2(src, ASSETS / src.name)
                copied.append((src.name, src.stat().st_size))

    # Metrics come from the run that actually ships.
    detect = test_metrics("detect_hn")
    reason = test_metrics("reason")
    leaky = test_metrics("reason_leaky")

    try:
        rf = json.loads((REPORTS / "legacy_rf.json").read_text())
        rf_honest = rf["honest_retrained_same_architecture"]["macro_auc"]
        rf_contaminated = rf["contaminated_shipped_pkl"]["macro_auc"]
    except FileNotFoundError:
        rf_honest = rf_contaminated = 0.0

    try:
        ablation = json.loads((REPORTS / "ablation.json").read_text())
        groupings = ablation.get("groupings", [])
    except FileNotFoundError:
        groupings = []
    best = max(groupings, key=lambda g: g["macro_auc"], default=None)

    trustworthy = reason["macro_auc"] >= TRUST_AUC_THRESHOLD

    kt = f'''package com.nila.audio

/**
 * GENERATED by ml/src/emit_android.py on {date.today().isoformat()} -- do not edit.
 *
 * These are the numbers our own evaluation produced, on a split where no infant
 * appears in both training and test. They are generated rather than typed so
 * that the reliability the app claims cannot drift from the reliability it was
 * measured to have.
 */
object ModelCard {{

    const val GENERATED_ON = "{date.today().isoformat()}"

    // ---- cry detection: deployable -------------------------------------
    const val DETECT_SUBJECT_WISE_AUC = {detect["macro_auc"]:.4f}f
    const val DETECT_ACCURACY = {detect["accuracy"]:.4f}f
    const val DETECT_BALANCED_ACCURACY = {detect["balanced_accuracy"]:.4f}f
    const val DETECT_MACRO_F1 = {detect["macro_f1"]:.4f}f
    const val DETECT_RECALL_CRY = {detect["per_class"]["cry"]["recall"]:.4f}f
    const val DETECT_RECALL_NOT_CRY = {detect["per_class"]["not_cry"]["recall"]:.4f}f
    const val DETECT_TEST_CLIPS = {detect["n"]}

    // ---- cry reason: measured, and it did not transfer ------------------
    const val REASON_SUBJECT_WISE_AUC = {reason["macro_auc"]:.4f}f
    const val REASON_ACCURACY = {reason["accuracy"]:.4f}f
    const val REASON_MACRO_F1 = {reason["macro_f1"]:.4f}f
    const val REASON_MAJORITY_BASELINE = {reason["majority_baseline"]:.4f}f
    const val REASON_TEST_CLIPS = {reason["n"]}

    /**
     * False when the reason head failed to beat chance on unseen infants.
     *
     * When this is false the UI must not print a cause as a fact. It may show
     * the hypothesis alongside this number, because a hypothesis carrying its
     * own validation result is honest; a bare label is not.
     */
    const val REASON_TRUSTWORTHY = {"true" if trustworthy else "false"}

    // ---- the same model under the protocol we argue against -------------
    const val REASON_LEAKY_AUC = {leaky["macro_auc"]:.4f}f
    const val REASON_LEAKY_ACCURACY = {leaky["accuracy"]:.4f}f

    /** What the evaluation protocol alone is worth, in macro AUC. */
    const val LEAKAGE_AUC_INFLATION = {leaky["macro_auc"] - reason["macro_auc"]:.4f}f

    // ---- an unrelated model family, same outcome ------------------------
    // A 461-feature Random Forest -- different features, different algorithm,
    // no shared code with the CNN -- lands in the same place on the same
    // infants. Two independent approaches failing identically is what turns
    // "our model did not work" into "this is not learnable from this data".
    const val RF_HONEST_AUC = {rf_honest:.4f}f
    const val RF_CONTAMINATED_AUC = {rf_contaminated:.4f}f

    // ---- best coarser grouping we could find ----------------------------
    const val BEST_GROUPING = "{best["grouping"] if best else "none"}"
    const val BEST_GROUPING_AUC = {best["macro_auc"] if best else 0.0:.4f}f

    /** One line, safe to put on screen, that states the limit plainly. */
    val honestSummary: String
        get() = if (REASON_TRUSTWORTHY) {{
            "Cause estimate validated at %.2f AUC on infants it has never heard."
                .format(REASON_SUBJECT_WISE_AUC)
        }} else {{
            // Parenthesised: `.format()` binds to the last literal in a `+`
            // chain, so an unparenthesised version silently leaves earlier
            // specifiers as literal text.
            (
                "We can tell you the baby is crying, not why. On infants it " +
                    "had never heard, the cause model scored %.2f AUC -- " +
                    "chance is 0.50."
                ).format(REASON_SUBJECT_WISE_AUC)
        }}
}}
'''
    KOTLIN.mkdir(parents=True, exist_ok=True)
    (KOTLIN / "ModelCard.kt").write_text(kt)

    print("\nassets:")
    for name, size in copied:
        print(f"  {name:26s} {size / 1024:8.1f} KB")
    print(f"\n  detect  subject-wise AUC {detect['macro_auc']:.4f}   -> deployable")
    print(f"  reason  subject-wise AUC {reason['macro_auc']:.4f}   "
          f"-> trustworthy={trustworthy}")
    print(f"  leakage inflation        {leaky['macro_auc'] - reason['macro_auc']:+.4f} AUC")
    print(f"\n  -> app/src/main/java/com/nila/audio/ModelCard.kt")


if __name__ == "__main__":
    main()
